linkboard/config/routes.rb
Rails.application.routes.draw do

  get '/comments' => 'comments#new'

  post '/comments' => 'comments#create'

  get '/comments' => 'comments#delete'

  root 'posts#index'

  post '/posts/new' => "posts#new"

  resources :posts, only: [:new, :create, :show, :destroy] do
    resources :comments, only: [:index, :new, :create, :destroy]
  end

  delete "/posts/:post_id/comments/:id" => "comments#destroy", as: "delete_post_comment"
  post "/posts/:post_id/comments/:id" => "comments#post"

  

  get '/signup' => "users#new"
  post '/signup' => "users#create"

  get '/login' => "sessions#new"
  post '/login' => "sessions#create"
  get '/logout' => "sessions#destroy"
  

end

linkboard/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

linkboard/app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title,
  presence: true,
  length: { 
  	minimum: 10,
  	maximum: 100
  }

  validates :link,
  presence: true,
  :url => true
end

linkboard/app/models/user.rb
class User < ActiveRecord::Base
	validates :email,
	presence: true,
	uniqueness: {case_sensitive: false},
	email: true

	has_many :posts
	has_many :comments

	validates :password,
	presence: true,
	length: {
		minimum: 8,
		maximum: 99
	}	,
	confirmation: true

	validates :name,
  		presence: true,
  		length: {
  			maximum: 20
  		}
  	validates_presence_of :password, on: :create
	has_secure_password

	def self.authenticate email, password
		User.find_by_email(email).try(:authenticate, password)
	end
end

linkboard/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :current_user

  def is_authenticated?
    unless current_user
      flash[:danger] = "Credentials Invalid!!"
      redirect_to login_path
    end
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end
  	
end

linkboard/app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index
		@post = Post.find params[:post_id]
		@comment = Comment.new

	end

  def new
  	redirect_to root_path
  end

  def create
  	 comment = Comment.create comment_params do |c|
  		c.user_id = @current_user.id
  		c.post_id = params[:post_id]
  		c.save
  	end
  	redirect_to root_path
  end

  def destroy
  	Comment.find(params[:id]).delete
  	redirect_to root_path
  end

  private
  def comment_params
  	params.require(:comment).permit(:post_id, :body, :user_id)
  end
end

linkboard/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_authenticated?, except: [:index, :destroy]

  def index
  	@posts = Post.all
    @comments = Comment.all
  end

  def new
  	@post= Post.new
  end

  def show
    redirect_to root_path
  end

  def create
  	# Post.create post_params
  	post = Post.create post_params do |p|
  		p.user_id = @current_user.id
  		p.save
  	end
    if post.valid?
      flash[:success] = 'Post created'
      redirect_to root_path
    else
      messages = post.errors.map { |k, v| "#{k} #{v}" }
      flash[:danger] = messages.join(', ')
      redirect_to new_post_path
    end
  end

  def destroy
    id =:params[:id]
    post = Post.find_by_id(id)
    post.destroy
    redirect_to root_path
  end

  private
  def post_params
  	params.require(:post).permit(:title, :link, :user_id)
  end
end

linkboard/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new

  end

  def create
  	user = User.authenticate login_params['email'], login_params['password']

		if user
			#do some stuff
			session[:user_id] = user.id
			flash[:success] = "#{user.email} has logged in!"
			redirect_to login_path
		else
			#give an error
			flash[:danger] = 'You had the wrong email/password'
			redirect_to login_path
		end
  end

  def destroy
  	session[:user_id] = nil
	redirect_to root_path
  end
  private

	def login_params
		params.require(:user).permit(:email, :password)
	end
end

linkboard/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
  	user = User.authenticate login_params['email'], login_params['password']

		if user
			user.id
			session[:user_id] = user.id
			flash[:success] = "#{user.email} has logged in!"
			redirect_to root_path
		else
			flash[:danger] = 'You had the wrong email/password'
			redirect_to login_path
		end
  end

  def destroy
  	session[:user_id] = nil
    flash[:success] = 'You have been logged out'
    redirect_to root_path
  end
  private

	def login_params
		params.require(:user).permit(:email, :password)
	end
end

linkboard/app/controllers/signup_controller.rb
class SignupController < ApplicationController
end

linkboard/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	User.create user_params
  	redirect_to root_path
  end

  private

	def user_params
		params.require(:user).permit(:email, :password, :name)
	end
end

linkboard/app/helpers/application_helper.rb
module ApplicationHelper
end

linkboard/app/helpers/comments_helper.rb
module CommentsHelper
end

linkboard/app/helpers/posts_helper.rb
module PostsHelper
end

linkboard/app/helpers/session_helper.rb
module SessionHelper
end

linkboard/app/helpers/signup_helper.rb
module SignupHelper
end

linkboard/app/helpers/users_helper.rb
module UsersHelper
end

linkboard/app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

linkboard/app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

linkboard/app/views/comments/index.html.erb
<h1>Create a new comment</h1>
<%= bootstrap_form_for [@post,@comment] do |c| %>
	<%= c.text_field :body, placeholder: 'Body'%>
	<%= c.submit 'Submit your post' %>
<% end %>

linkboard/app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

linkboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Linkboard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS & JS -->
  	<link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/	bootstrap.css">
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
	 <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>
</head>
<body>
<div class="container">
<nav class="navbar navbar-dark bg-primary">
  <a class="navbar-brand" href="/">Geek wire posts</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
    </li>
    <% if @current_user %>
        <li class="nav-item"><%= link_to 'Logout', logout_path, class: "nav-link" %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Signup', signup_path, class: "nav-link" %></li>
        <li class="nav-item"><%= link_to 'Login', login_path, class: "nav-link" %></li>
      <% end %>
    <li class="nav-item">
      <a class="nav-link" href="/posts/new">Create new post</a>
    </li>
  </ul>
</nav>
<%= render "partials/flash" %>
<%= yield %>
</div>
</body>
</html>

linkboard/app/views/partials/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <%= value %>
  </div>
<% end %>

linkboard/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

linkboard/app/views/posts/index.html.erb
<span>
	<h1>Come look at all the fun posts!</h1>
</span>

<% @posts.each do |post|%>
	<div class="card post">
		<h2><a href="<%= post.link%>"><%=post.title%></a></h2>
		<p>By:<%= post.user.name %></p>
		<%=link_to "Delete", {:controller => "posts", :action => "destroy", :id => post.id}, class: "delete_btn"%>
		<a href="/posts/<%=post.id%>/comments"><button>Comment</button></a>
		<h3>Comments so far!</h3>
		<% @comments.each do |comment| %>
			<% if comment.post_id == post.id %>
				<h4><%=comment.user.name%></h4>
				<p><%=comment.body%></p>
				<%= link_to 'Delete Comment', delete_post_comment_path(post.id, comment.id), class: 'btn btn-danger', method: :delete %>
			<%end%>
		<%end%>
	</div>
<%end%>

linkboard/app/views/posts/new.html.erb
<h1>Create a new post</h1>
<%= bootstrap_form_for @post, url: posts_path do |f| %>
	<%= f.text_field :title, placeholder: 'Title'%>
	<%= f.text_field :link, placeholder: 'Link'%>
	<%= f.submit 'Submit your post' %>
<% end %>

linkboard/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

linkboard/app/views/users/new.html.erb
<h1>Sign up here!</h1>

<%= bootstrap_form_for :user do |f| %>
	<%= f.text_field :email, placeholder: 'Email'%>
	<%= f.password_field :password, placeholder: 'password' %>
	<%= f.text_field :name, placeholder: 'name'%>
	<%= f.submit 'Sign me up!' %>
<% end %>